delete from KenPomMapping;
insert into KenPomMapping(Team,ncaaTeam) values ('Air Force','Air Force');
insert into KenPomMapping(Team,ncaaTeam) values ('Akron','Akron');
insert into KenPomMapping(Team,ncaaTeam) values ('Alabama','Alabama');
insert into KenPomMapping(Team,ncaaTeam) values ('Alabama A&M','Alabama A&M');
insert into KenPomMapping(Team,ncaaTeam) values ('Alabama St.','Alabama St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Albany','Albany (NY)');
insert into KenPomMapping(Team,ncaaTeam) values ('Alcorn St.','Alcorn');
insert into KenPomMapping(Team,ncaaTeam) values ('American','American');
insert into KenPomMapping(Team,ncaaTeam) values ('Appalachian St.','Appalachian St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Arizona','Arizona');
insert into KenPomMapping(Team,ncaaTeam) values ('Arizona St.','Arizona St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Arkansas','Arkansas');
insert into KenPomMapping(Team,ncaaTeam) values ('Arkansas Little Rock','UALR');
insert into KenPomMapping(Team,ncaaTeam) values ('Arkansas Pine Bluff','Ark.-Pine Bluff');
insert into KenPomMapping(Team,ncaaTeam) values ('Arkansas St.','Arkansas St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Army','Army');
insert into KenPomMapping(Team,ncaaTeam) values ('Auburn','Auburn');
insert into KenPomMapping(Team,ncaaTeam) values ('Austin Peay','Austin Peay');
insert into KenPomMapping(Team,ncaaTeam) values ('Ball St.','Ball St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Baylor','Baylor');
insert into KenPomMapping(Team,ncaaTeam) values ('Belmont','Belmont');
insert into KenPomMapping(Team,ncaaTeam) values ('Bethune Cookman','Bethune-Cookman');
insert into KenPomMapping(Team,ncaaTeam) values ('Binghamton','Binghamton');
insert into KenPomMapping(Team,ncaaTeam) values ('Boise St.','Boise St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Boston College','Boston College');
insert into KenPomMapping(Team,ncaaTeam) values ('Boston University','Boston U.');
insert into KenPomMapping(Team,ncaaTeam) values ('Bowling Green','Bowling Green');
insert into KenPomMapping(Team,ncaaTeam) values ('Bradley','Bradley');
insert into KenPomMapping(Team,ncaaTeam) values ('Brigham Young','BYU');
insert into KenPomMapping(Team,ncaaTeam) values ('Brown','Brown');
insert into KenPomMapping(Team,ncaaTeam) values ('Bryant','Bryant');
insert into KenPomMapping(Team,ncaaTeam) values ('Bucknell','Bucknell');
insert into KenPomMapping(Team,ncaaTeam) values ('Buffalo','Buffalo');
insert into KenPomMapping(Team,ncaaTeam) values ('Butler','Butler');
insert into KenPomMapping(Team,ncaaTeam) values ('Cal Poly','Cal Poly');
insert into KenPomMapping(Team,ncaaTeam) values ('Cal St. Bakersfield','CSU Bakersfield');
insert into KenPomMapping(Team,ncaaTeam) values ('Cal St. Fullerton','Cal St. Fullerton');
insert into KenPomMapping(Team,ncaaTeam) values ('Cal St. Northridge','Cal St. Northridge');
insert into KenPomMapping(Team,ncaaTeam) values ('California','California');
insert into KenPomMapping(Team,ncaaTeam) values ('Campbell','Campbell');
insert into KenPomMapping(Team,ncaaTeam) values ('Canisius','Canisius');
insert into KenPomMapping(Team,ncaaTeam) values ('Central Arkansas','Central Ark.');
insert into KenPomMapping(Team,ncaaTeam) values ('Central Connecticut','Central Conn. St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Central Florida','UCF');
insert into KenPomMapping(Team,ncaaTeam) values ('Central Michigan','Central Mich.');
insert into KenPomMapping(Team,ncaaTeam) values ('Charleston Southern','Charleston So.');
insert into KenPomMapping(Team,ncaaTeam) values ('Charlotte','Charlotte');
insert into KenPomMapping(Team,ncaaTeam) values ('Chattanooga','Chattanooga');
insert into KenPomMapping(Team,ncaaTeam) values ('Chicago St.','Chicago St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Cincinnati','Cincinnati');
insert into KenPomMapping(Team,ncaaTeam) values ('Clemson','Clemson');
insert into KenPomMapping(Team,ncaaTeam) values ('Cleveland St.','Cleveland St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Coastal Carolina','Coastal Caro.');
insert into KenPomMapping(Team,ncaaTeam) values ('Colgate','Colgate');
insert into KenPomMapping(Team,ncaaTeam) values ('College of Charleston','Col. of Charleston');
insert into KenPomMapping(Team,ncaaTeam) values ('Colorado','Colorado');
insert into KenPomMapping(Team,ncaaTeam) values ('Colorado St.','Colorado St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Columbia','Columbia');
insert into KenPomMapping(Team,ncaaTeam) values ('Connecticut','Connecticut');
insert into KenPomMapping(Team,ncaaTeam) values ('Coppin St.','Coppin St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Cornell','Cornell');
insert into KenPomMapping(Team,ncaaTeam) values ('Creighton','Creighton');
insert into KenPomMapping(Team,ncaaTeam) values ('Dartmouth','Dartmouth');
insert into KenPomMapping(Team,ncaaTeam) values ('Davidson','Davidson');
insert into KenPomMapping(Team,ncaaTeam) values ('Dayton','Dayton');
insert into KenPomMapping(Team,ncaaTeam) values ('Delaware','Delaware');
insert into KenPomMapping(Team,ncaaTeam) values ('Delaware St.','Delaware St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Denver','Denver');
insert into KenPomMapping(Team,ncaaTeam) values ('DePaul','DePaul');
insert into KenPomMapping(Team,ncaaTeam) values ('Detroit','Detroit');
insert into KenPomMapping(Team,ncaaTeam) values ('Drake','Drake');
insert into KenPomMapping(Team,ncaaTeam) values ('Drexel','Drexel');
insert into KenPomMapping(Team,ncaaTeam) values ('Duke','Duke');
insert into KenPomMapping(Team,ncaaTeam) values ('Duquesne','Duquesne');
insert into KenPomMapping(Team,ncaaTeam) values ('East Carolina','East Carolina');
insert into KenPomMapping(Team,ncaaTeam) values ('East Tennessee St.','East Tenn. St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Eastern Illinois','Eastern Ill.');
insert into KenPomMapping(Team,ncaaTeam) values ('Eastern Kentucky','Eastern Ky.');
insert into KenPomMapping(Team,ncaaTeam) values ('Eastern Michigan','Eastern Mich.');
insert into KenPomMapping(Team,ncaaTeam) values ('Eastern Washington','Eastern Wash.');
insert into KenPomMapping(Team,ncaaTeam) values ('Elon','Elon');
insert into KenPomMapping(Team,ncaaTeam) values ('Evansville','Evansville');
insert into KenPomMapping(Team,ncaaTeam) values ('Fairfield','Fairfield');
insert into KenPomMapping(Team,ncaaTeam) values ('Fairleigh Dickinson','Fairleigh Dickinson');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida','Florida');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida A&M','Florida A&M');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida Atlantic','Fla. Atlantic');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida Gulf Coast','FGCU');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida International','FIU');
insert into KenPomMapping(Team,ncaaTeam) values ('Florida St.','Florida St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Fordham','Fordham');
insert into KenPomMapping(Team,ncaaTeam) values ('Fresno St.','Fresno St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Furman','Furman');
insert into KenPomMapping(Team,ncaaTeam) values ('Gardner Webb','Gardner-Webb');
insert into KenPomMapping(Team,ncaaTeam) values ('George Mason','George Mason');
insert into KenPomMapping(Team,ncaaTeam) values ('George Washington','George Washington');
insert into KenPomMapping(Team,ncaaTeam) values ('Georgetown','Georgetown');
insert into KenPomMapping(Team,ncaaTeam) values ('Georgia','Georgia');
insert into KenPomMapping(Team,ncaaTeam) values ('Georgia Southern','Ga. Southern');
insert into KenPomMapping(Team,ncaaTeam) values ('Georgia St.','Georgia St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Georgia Tech','Georgia Tech');
insert into KenPomMapping(Team,ncaaTeam) values ('Gonzaga','Gonzaga');
insert into KenPomMapping(Team,ncaaTeam) values ('Grambling','Grambling');
insert into KenPomMapping(Team,ncaaTeam) values ('Hampton','Hampton');
insert into KenPomMapping(Team,ncaaTeam) values ('Hartford','Hartford');
insert into KenPomMapping(Team,ncaaTeam) values ('Harvard','Harvard');
insert into KenPomMapping(Team,ncaaTeam) values ('Hawaii','Hawaii');
insert into KenPomMapping(Team,ncaaTeam) values ('High Point','High Point');
insert into KenPomMapping(Team,ncaaTeam) values ('Hofstra','Hofstra');
insert into KenPomMapping(Team,ncaaTeam) values ('Holy Cross','Holy Cross');
insert into KenPomMapping(Team,ncaaTeam) values ('Houston','Houston');
insert into KenPomMapping(Team,ncaaTeam) values ('Houston Baptist','Houston Baptist');
insert into KenPomMapping(Team,ncaaTeam) values ('Howard','Howard');
insert into KenPomMapping(Team,ncaaTeam) values ('Idaho','Idaho');
insert into KenPomMapping(Team,ncaaTeam) values ('Idaho St.','Idaho St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Illinois','Illinois');
insert into KenPomMapping(Team,ncaaTeam) values ('Illinois Chicago','Ill.-Chicago');
insert into KenPomMapping(Team,ncaaTeam) values ('Illinois St.','Illinois St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Indiana','Indiana');
insert into KenPomMapping(Team,ncaaTeam) values ('Indiana St.','Indiana St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Iona','Iona');
insert into KenPomMapping(Team,ncaaTeam) values ('Iowa','Iowa');
insert into KenPomMapping(Team,ncaaTeam) values ('Iowa St.','Iowa St.');
insert into KenPomMapping(Team,ncaaTeam) values ('IUPU Fort Wayne','IPFW');
insert into KenPomMapping(Team,ncaaTeam) values ('IUPUI','IUPUI');
insert into KenPomMapping(Team,ncaaTeam) values ('Jackson St.','Jackson St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Jacksonville','Jacksonville');
insert into KenPomMapping(Team,ncaaTeam) values ('Jacksonville St.','Jacksonville St.');
insert into KenPomMapping(Team,ncaaTeam) values ('James Madison','James Madison');
insert into KenPomMapping(Team,ncaaTeam) values ('Kansas','Kansas');
insert into KenPomMapping(Team,ncaaTeam) values ('Kansas St.','Kansas St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Kennesaw St.','Kennesaw St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Kent St.','Kent St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Kentucky','Kentucky');
insert into KenPomMapping(Team,ncaaTeam) values ('La Salle','La Salle');
insert into KenPomMapping(Team,ncaaTeam) values ('Lafayette','Lafayette');
insert into KenPomMapping(Team,ncaaTeam) values ('Lamar','Lamar');
insert into KenPomMapping(Team,ncaaTeam) values ('Lehigh','Lehigh');
insert into KenPomMapping(Team,ncaaTeam) values ('Liberty','Liberty');
insert into KenPomMapping(Team,ncaaTeam) values ('Lipscomb','Lipscomb');
insert into KenPomMapping(Team,ncaaTeam) values ('Long Beach St.','Long Beach St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Long Island','LIU Brooklyn');
insert into KenPomMapping(Team,ncaaTeam) values ('Longwood','Longwood');
insert into KenPomMapping(Team,ncaaTeam) values ('Louisiana Lafayette','La.-Lafayette');
insert into KenPomMapping(Team,ncaaTeam) values ('Louisiana Monroe','La.-Monroe');
insert into KenPomMapping(Team,ncaaTeam) values ('Louisiana St.','LSU');
insert into KenPomMapping(Team,ncaaTeam) values ('Louisiana Tech','Louisiana Tech');
insert into KenPomMapping(Team,ncaaTeam) values ('Louisville','Louisville');
insert into KenPomMapping(Team,ncaaTeam) values ('Loyola Chicago','Loyola Chicago');
insert into KenPomMapping(Team,ncaaTeam) values ('Loyola Marymount','Loyola Marymount');
insert into KenPomMapping(Team,ncaaTeam) values ('Loyola MD','Loyola Maryland');
insert into KenPomMapping(Team,ncaaTeam) values ('Maine','Maine');
insert into KenPomMapping(Team,ncaaTeam) values ('Manhattan','Manhattan');
insert into KenPomMapping(Team,ncaaTeam) values ('Marist','Marist');
insert into KenPomMapping(Team,ncaaTeam) values ('Marquette','Marquette');
insert into KenPomMapping(Team,ncaaTeam) values ('Marshall','Marshall');
insert into KenPomMapping(Team,ncaaTeam) values ('Maryland','Maryland');
insert into KenPomMapping(Team,ncaaTeam) values ('Maryland Eastern Shore','UMES');
insert into KenPomMapping(Team,ncaaTeam) values ('Massachusetts','Massachusetts');
insert into KenPomMapping(Team,ncaaTeam) values ('McNeese St.','McNeese St.');
insert into KenPomMapping(Team,ncaaTeam) values ('MD Baltimore County','UMBC');
insert into KenPomMapping(Team,ncaaTeam) values ('Memphis','Memphis');
insert into KenPomMapping(Team,ncaaTeam) values ('Mercer','Mercer');
insert into KenPomMapping(Team,ncaaTeam) values ('Miami FL','Miami (FL)');
insert into KenPomMapping(Team,ncaaTeam) values ('Miami OH','Miami (OH)');
insert into KenPomMapping(Team,ncaaTeam) values ('Michigan','Michigan');
insert into KenPomMapping(Team,ncaaTeam) values ('Michigan St.','Michigan St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Middle Tennessee','Middle Tenn.');
insert into KenPomMapping(Team,ncaaTeam) values ('Minnesota','Minnesota');
insert into KenPomMapping(Team,ncaaTeam) values ('Mississippi','Ole Miss');
insert into KenPomMapping(Team,ncaaTeam) values ('Mississippi St.','Mississippi St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Mississippi Valley St.','Mississippi Val.');
insert into KenPomMapping(Team,ncaaTeam) values ('Missouri','Missouri');
insert into KenPomMapping(Team,ncaaTeam) values ('Missouri Kansas City','UMKC');
insert into KenPomMapping(Team,ncaaTeam) values ('Missouri St.','Missouri St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Monmouth','Monmouth');
insert into KenPomMapping(Team,ncaaTeam) values ('Montana','Montana');
insert into KenPomMapping(Team,ncaaTeam) values ('Montana St.','Montana St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Morehead St.','Morehead St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Morgan St.','Morgan St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Mount St. Mary''s','Mt. St. Mary''s');
insert into KenPomMapping(Team,ncaaTeam) values ('Murray St.','Murray St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Navy','Navy');
insert into KenPomMapping(Team,ncaaTeam) values ('NC Asheville','UNC Asheville');
insert into KenPomMapping(Team,ncaaTeam) values ('NC Greensboro','UNC Greensboro');
insert into KenPomMapping(Team,ncaaTeam) values ('NC Wilmington','UNC Wilmington');
insert into KenPomMapping(Team,ncaaTeam) values ('Nebraska','Nebraska');
insert into KenPomMapping(Team,ncaaTeam) values ('Nebraska Omaha','Neb. Omaha');
insert into KenPomMapping(Team,ncaaTeam) values ('Nevada','Nevada');
insert into KenPomMapping(Team,ncaaTeam) values ('Nevada Las Vegas','UNLV');
insert into KenPomMapping(Team,ncaaTeam) values ('New Hampshire','New Hampshire');
insert into KenPomMapping(Team,ncaaTeam) values ('New Mexico','New Mexico');
insert into KenPomMapping(Team,ncaaTeam) values ('New Mexico St.','New Mexico St.');
insert into KenPomMapping(Team,ncaaTeam) values ('New Orleans','New Orleans');
insert into KenPomMapping(Team,ncaaTeam) values ('Niagara','Niagara');
insert into KenPomMapping(Team,ncaaTeam) values ('Nicholls St.','Nicholls St.');
insert into KenPomMapping(Team,ncaaTeam) values ('NJ Inst of Technology','NJIT');
insert into KenPomMapping(Team,ncaaTeam) values ('Norfolk St.','Norfolk St.');
insert into KenPomMapping(Team,ncaaTeam) values ('North Carolina','North Carolina');
insert into KenPomMapping(Team,ncaaTeam) values ('North Carolina A&T','N.C. A&T');
insert into KenPomMapping(Team,ncaaTeam) values ('North Carolina Central','N.C. Central');
insert into KenPomMapping(Team,ncaaTeam) values ('North Carolina St.','North Carolina St.');
insert into KenPomMapping(Team,ncaaTeam) values ('North Dakota','North Dakota');
insert into KenPomMapping(Team,ncaaTeam) values ('North Dakota St.','North Dakota St.');
insert into KenPomMapping(Team,ncaaTeam) values ('North Florida','North Florida');
insert into KenPomMapping(Team,ncaaTeam) values ('North Texas','North Texas');
insert into KenPomMapping(Team,ncaaTeam) values ('Northeastern','Northeastern');
insert into KenPomMapping(Team,ncaaTeam) values ('Northern Arizona','Northern Ariz.');
insert into KenPomMapping(Team,ncaaTeam) values ('Northern Colorado','Northern Colo.');
insert into KenPomMapping(Team,ncaaTeam) values ('Northern Illinois','Northern Ill.');
insert into KenPomMapping(Team,ncaaTeam) values ('Northern Iowa','UNI');
insert into KenPomMapping(Team,ncaaTeam) values ('Northern Kentucky','Northern Ky.');
insert into KenPomMapping(Team,ncaaTeam) values ('Northwestern','Northwestern');
insert into KenPomMapping(Team,ncaaTeam) values ('Northwestern St.','Northwestern St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Notre Dame','Notre Dame');
insert into KenPomMapping(Team,ncaaTeam) values ('Oakland','Oakland');
insert into KenPomMapping(Team,ncaaTeam) values ('Ohio','Ohio');
insert into KenPomMapping(Team,ncaaTeam) values ('Ohio St.','Ohio St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Oklahoma','Oklahoma');
insert into KenPomMapping(Team,ncaaTeam) values ('Oklahoma St.','Oklahoma St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Old Dominion','Old Dominion');
insert into KenPomMapping(Team,ncaaTeam) values ('Oral Roberts','Oral Roberts');
insert into KenPomMapping(Team,ncaaTeam) values ('Oregon','Oregon');
insert into KenPomMapping(Team,ncaaTeam) values ('Oregon St.','Oregon St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Pacific','Pacific');
insert into KenPomMapping(Team,ncaaTeam) values ('Penn St.','Penn St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Pennsylvania','Penn');
insert into KenPomMapping(Team,ncaaTeam) values ('Pepperdine','Pepperdine');
insert into KenPomMapping(Team,ncaaTeam) values ('Pittsburgh','Pittsburgh');
insert into KenPomMapping(Team,ncaaTeam) values ('Portland','Portland');
insert into KenPomMapping(Team,ncaaTeam) values ('Portland St.','Portland St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Prairie View A&M','Prairie View');
insert into KenPomMapping(Team,ncaaTeam) values ('Presbyterian','Presbyterian');
insert into KenPomMapping(Team,ncaaTeam) values ('Princeton','Princeton');
insert into KenPomMapping(Team,ncaaTeam) values ('Providence','Providence');
insert into KenPomMapping(Team,ncaaTeam) values ('Purdue','Purdue');
insert into KenPomMapping(Team,ncaaTeam) values ('Quinnipiac','Quinnipiac');
insert into KenPomMapping(Team,ncaaTeam) values ('Radford','Radford');
insert into KenPomMapping(Team,ncaaTeam) values ('Rhode Island','Rhode Island');
insert into KenPomMapping(Team,ncaaTeam) values ('Rice','Rice');
insert into KenPomMapping(Team,ncaaTeam) values ('Richmond','Richmond');
insert into KenPomMapping(Team,ncaaTeam) values ('Rider','Rider');
insert into KenPomMapping(Team,ncaaTeam) values ('Robert Morris','Robert Morris');
insert into KenPomMapping(Team,ncaaTeam) values ('Rutgers','Rutgers');
insert into KenPomMapping(Team,ncaaTeam) values ('Sacramento St.','Sacramento St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Sacred Heart','Sacred Heart');
insert into KenPomMapping(Team,ncaaTeam) values ('Saint Joseph''s','Saint Joseph''s');
insert into KenPomMapping(Team,ncaaTeam) values ('Sam Houston St.','Sam Houston St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Samford','Samford');
insert into KenPomMapping(Team,ncaaTeam) values ('San Diego','San Diego');
insert into KenPomMapping(Team,ncaaTeam) values ('San Diego St.','San Diego St.');
insert into KenPomMapping(Team,ncaaTeam) values ('San Francisco','San Francisco');
insert into KenPomMapping(Team,ncaaTeam) values ('San Jose St.','San Jose St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Santa Clara','Santa Clara');
insert into KenPomMapping(Team,ncaaTeam) values ('Savannah St.','Savannah St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Seattle','Seattle');
insert into KenPomMapping(Team,ncaaTeam) values ('Seton Hall','Seton Hall');
insert into KenPomMapping(Team,ncaaTeam) values ('Siena','Siena');
insert into KenPomMapping(Team,ncaaTeam) values ('SIU Edwardsville','SIU Edwardsville');
insert into KenPomMapping(Team,ncaaTeam) values ('South Alabama','South Ala.');
insert into KenPomMapping(Team,ncaaTeam) values ('South Carolina','South Carolina');
insert into KenPomMapping(Team,ncaaTeam) values ('South Carolina St.','South Carolina St.');
insert into KenPomMapping(Team,ncaaTeam) values ('South Carolina Upstate','USC Upstate');
insert into KenPomMapping(Team,ncaaTeam) values ('South Dakota','South Dakota');
insert into KenPomMapping(Team,ncaaTeam) values ('South Dakota St.','South Dakota St.');
insert into KenPomMapping(Team,ncaaTeam) values ('South Florida','South Fla.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southeast Missouri St.','Southeast Mo. St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southeastern Louisiana','Southeastern La.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern','Southern U.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern California','Southern California');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern Illinois','Southern Ill.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern Methodist','SMU');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern Mississippi','Southern Miss.');
insert into KenPomMapping(Team,ncaaTeam) values ('Southern Utah','Southern Utah');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Bonaventure','St. Bonaventure');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Francis NY','St. Francis Brooklyn');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Francis PA','Saint Francis (PA)');
insert into KenPomMapping(Team,ncaaTeam) values ('St. John''s','St. John''s (NY)');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Louis','Saint Louis');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Mary''s','St. Mary''s (CA)');
insert into KenPomMapping(Team,ncaaTeam) values ('St. Peter''s','Saint Peter''s');
insert into KenPomMapping(Team,ncaaTeam) values ('Stanford','Stanford');
insert into KenPomMapping(Team,ncaaTeam) values ('Stephen F. Austin','Stephen F. Austin');
insert into KenPomMapping(Team,ncaaTeam) values ('Stetson','Stetson');
insert into KenPomMapping(Team,ncaaTeam) values ('Stony Brook','Stony Brook');
insert into KenPomMapping(Team,ncaaTeam) values ('Syracuse','Syracuse');
insert into KenPomMapping(Team,ncaaTeam) values ('Temple','Temple');
insert into KenPomMapping(Team,ncaaTeam) values ('Tennessee','Tennessee');
insert into KenPomMapping(Team,ncaaTeam) values ('Tennessee Martin','UT Martin');
insert into KenPomMapping(Team,ncaaTeam) values ('Tennessee St.','Tennessee St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Tennessee Tech','Tennessee Tech');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas','Texas');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas A&M','Texas A&M');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas A&M Corpus Chris','A&M-Corpus Chris');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas Arlington','Texas-Arlington');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas Christian','TCU');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas El Paso','UTEP');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas Pan American','Tex.-Pan American');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas San Antonio','UTSA');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas Southern','Texas Southern');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas St.','Texas St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Texas Tech','Texas Tech');
insert into KenPomMapping(Team,ncaaTeam) values ('The Citadel','Citadel');
insert into KenPomMapping(Team,ncaaTeam) values ('Toledo','Toledo');
insert into KenPomMapping(Team,ncaaTeam) values ('Towson','Towson');
insert into KenPomMapping(Team,ncaaTeam) values ('Troy','Troy');
insert into KenPomMapping(Team,ncaaTeam) values ('Tulane','Tulane');
insert into KenPomMapping(Team,ncaaTeam) values ('Tulsa','Tulsa');
insert into KenPomMapping(Team,ncaaTeam) values ('UAB','UAB');
insert into KenPomMapping(Team,ncaaTeam) values ('UC Davis','UC Davis');
insert into KenPomMapping(Team,ncaaTeam) values ('UC Irvine','UC Irvine');
insert into KenPomMapping(Team,ncaaTeam) values ('UC Riverside','UC Riverside');
insert into KenPomMapping(Team,ncaaTeam) values ('UC Santa Barbara','UC Santa Barbara');
insert into KenPomMapping(Team,ncaaTeam) values ('UCLA','UCLA');
insert into KenPomMapping(Team,ncaaTeam) values ('Utah','Utah');
insert into KenPomMapping(Team,ncaaTeam) values ('Utah St.','Utah St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Utah Valley','Utah Valley');
insert into KenPomMapping(Team,ncaaTeam) values ('Valparaiso','Valparaiso');
insert into KenPomMapping(Team,ncaaTeam) values ('Vanderbilt','Vanderbilt');
insert into KenPomMapping(Team,ncaaTeam) values ('Vermont','Vermont');
insert into KenPomMapping(Team,ncaaTeam) values ('Villanova','Villanova');
insert into KenPomMapping(Team,ncaaTeam) values ('Virginia','Virginia');
insert into KenPomMapping(Team,ncaaTeam) values ('Virginia Commonwealth','VCU');
insert into KenPomMapping(Team,ncaaTeam) values ('Virginia Military Inst','VMI');
insert into KenPomMapping(Team,ncaaTeam) values ('Virginia Tech','Virginia Tech');
insert into KenPomMapping(Team,ncaaTeam) values ('Wagner','Wagner');
insert into KenPomMapping(Team,ncaaTeam) values ('Wake Forest','Wake Forest');
insert into KenPomMapping(Team,ncaaTeam) values ('Washington','Washington');
insert into KenPomMapping(Team,ncaaTeam) values ('Washington St.','Washington St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Weber St.','Weber St.');
insert into KenPomMapping(Team,ncaaTeam) values ('West Virginia','West Virginia');
insert into KenPomMapping(Team,ncaaTeam) values ('Western Carolina','Western Caro.');
insert into KenPomMapping(Team,ncaaTeam) values ('Western Illinois','Western Ill.');
insert into KenPomMapping(Team,ncaaTeam) values ('Western Kentucky','Western Ky.');
insert into KenPomMapping(Team,ncaaTeam) values ('Western Michigan','Western Mich.');
insert into KenPomMapping(Team,ncaaTeam) values ('Wichita St.','Wichita St.');
insert into KenPomMapping(Team,ncaaTeam) values ('William & Mary','William & Mary');
insert into KenPomMapping(Team,ncaaTeam) values ('Winthrop','Winthrop');
insert into KenPomMapping(Team,ncaaTeam) values ('Wisconsin','Wisconsin');
insert into KenPomMapping(Team,ncaaTeam) values ('Wisconsin Green Bay','Green Bay');
insert into KenPomMapping(Team,ncaaTeam) values ('Wisconsin Milwaukee','Milwaukee');
insert into KenPomMapping(Team,ncaaTeam) values ('Wofford','Wofford');
insert into KenPomMapping(Team,ncaaTeam) values ('Wright St.','Wright St.');
insert into KenPomMapping(Team,ncaaTeam) values ('Wyoming','Wyoming');
insert into KenPomMapping(Team,ncaaTeam) values ('Xavier','Xavier');
insert into KenPomMapping(Team,ncaaTeam) values ('Yale','Yale');
insert into KenPomMapping(Team,ncaaTeam) values ('Youngstown St.','Youngstown St.');
